# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# to reset password: htpasswd -s -b -n internal changeme
openshift_prometheus_htpasswd_auth: internal:{SHA}+pvrmeQCmtWmYVOZ57uuITVghrM=
openshift_prometheus_basic_auth_pass: changeme
extra_prometheus_hosts:

# Uncomment this if your cluster serves privately signed certificates
# custom_ca: true

deployment:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: pelorus
    app.kubernetes.io/version: v0.33.0

exporters:
  instances:
    - app_name: deploytime-exporter
      source_context_dir: exporters/
      extraEnv:
        - name: APP_FILE
          value: deploytime/app.py
        #        - name: APP_LABEL
        #          value: pelorus/app.name
        - name: NAMESPACES
          value: gitops-demo-cicd,gitops-demo-stage,gitops-demo-dev
        - name: LOG_LEVEL
          value: DEBUG
      source_ref: master
      source_url: http://github.com/adnan-drina/pelorus.git
    - app_name: committime-exporter
      env_from_secrets:
        - github-secret
      source_context_dir: exporters/
      extraEnv:
        - name: APP_FILE
          value: committime/app.py
        - name: NAMESPACES
          value: gitops-demo-cicd,gitops-demo-stage,gitops-demo-dev
        - name: LOG_LEVEL
          value: DEBUG
      source_ref: master
      source_url: https://github.com/adnan-drina/pelorus.git
    - app_name: failure-exporter
      env_from_secrets:
        - jira-secret
      source_context_dir: exporters/
      extraEnv:
        - name: APP_FILE
          value: failure/app.py
        - name: NAMESPACES
          value: gitops-demo-cicd,gitops-demo-stage,gitops-demo-dev
        - name: LOG_LEVEL
          value: DEBUG
      source_ref: master
      source_url: https://github.com/adnan-drina/pelorus.git

snapshot_schedule: "@monthly"